# Generated by Django 5.2 on 2025-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
